FROM debian:8.6

RUN  \
     mkdir -v out && \
     cd out && \

     mkdir -v etc usr && \
     ln -s /bin sbin && \
     ln -s /bin usr/bin && \

     echo root:x:0:0:root:/:/bin/sh > etc/passwd && \
     echo root:x:0: > etc/group && \

     tar czfv /rootfs.tar.gz ./*